[tool.poetry]
name = "homeserver"
version = "0.1.0"
description = ""
authors = ["VladSkopenko <skopirka2k17@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
